name: build-images

on:
  push:
    branches: [main]

jobs:
  docker-hub:
    uses: ./.github/workflows/build-image-template.yml
    secrets:
      dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}
    with:
      docker-file: Dockerfile.hub
      image-name: softwareimprovementgroup/sigridci:latest

  docker-azure:
    uses: ./.github/workflows/build-image-template.yml
    secrets:
      dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}
    with:
      docker-file: Dockerfile.Azure
      image-name: softwareimprovementgroup/sigridci:azure

  docker-actions-test-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: Build
        uses: docker/build-push-action@f9f3042f7e2789586610d6e8b85c8f03e5195baf # v7.2.0
        with:
          file: Dockerfile
