name: build-images

on:
  push:
    branches: [main]

jobs:
  docker-hub:
    uses: ./.github/workflows/build-image-template.yml
    secrets:
      dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}
    with:
      docker-file: Dockerfile.hub
      image-name: softwareimprovementgroup/sigridci:latest

  docker-azure:
    uses: ./.github/workflows/build-image-template.yml
    secrets:
      dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}
    with:
      docker-file: Dockerfile.Azure
      image-name: softwareimprovementgroup/sigridci:azure

  docker-actions-test-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Build
        uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7.3.0
        with:
          file: Dockerfile
