name: build-images

on:
  push:

jobs:
  docker-hub:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4

      -
        name: Build
        uses: docker/build-push-action@v6
        with:
          file: Dockerfile.hub
  docker-azure:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4

      -
        name: Build
        uses: docker/build-push-action@v6
        with:
          file: Dockerfile.Azure
  docker-actions:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4

      -
        name: Build
        uses: docker/build-push-action@v6
        with:
          file: Dockerfile