name: build-images

on:
  push:
    branches: [main]

jobs:
  docker-hub:
    uses: ./.github/workflows/build-image-template.yml
    secrets:
      dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}
    with:
      docker-file: Dockerfile.hub
      image-name: softwareimprovementgroup/sigridci:latest

  docker-azure:
    uses: ./.github/workflows/build-image-template.yml
    secrets:
      dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}
    with:
      docker-file: Dockerfile.Azure
      image-name: softwareimprovementgroup/sigridci:azure

  docker-actions-test-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        uses: docker/build-push-action@d08e5c354a6adb9ed34480a06d141179aa583294 # v7.0.0
        with:
          file: Dockerfile
