name: "Slack alerts for Sigrid findings"
on:
  schedule:
    - cron: "0 6 * * 1-5"
jobs:
  slackalerts:
    name: "Send Slack alerts"
    runs-on: ubuntu-latest
    steps:
      - name: "Check out repository"
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          repository: "Software-Improvement-Group/sigrid-integrations"
      - run: "./slack-security-findings/daily_findings.py --customer sig --system sigridci-client"
        env:
          SIGRID_CI_TOKEN: "${{ secrets.SIGRID_CI_TOKEN }}"
          SECURITY_FINDINGS_WEBHOOK: "${{ secrets.SECURITY_FINDINGS_WEBHOOK }}"
